### PR TITLE
fix: handle datepicker association reliably

### LINKED ISSUE #3331: [Bug]: datepicker arrow disabled after browser navigation
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.16.0

### Operating system

Windows 11 Enterprise 23H2

### Browser / Browser version

Chrome 131.0.6778.205 (64-Bit)

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

If navigating from a page using the datepicker (https://www.sbb.ch/de > "Billette wählen") and navigating back via Browser Funktion (Alt + Arrow left) both Datepicker-Arrows prev und next are disabled. The calendar itself is not disabled.

This Bug does not appear:
-  on Firefox 133.0.3 (64-Bit) or Sarafi. 
- by navigating via menu
- on page reload
- if selected date != default date (=today), regardless of using calendar or datepicker-arrows for selection

### Steps to reproduce the issue

1. not changing datepicker-date or changing datepicker-date back to default date
2. nafigating from sbb.ch/de to sbb.ch/de/angebot vir "Billette wählen"
3. navigating back to sbb.ch vie browser (arrow back or Alt + Arrow left)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kyubisation**
Closes #3331

### CODE REVIEW

File: src/elements/datepicker/datepicker/datepicker.ts [hunk 1]
```diff
@@ -33,6 +33,7 @@ export interface SbbInputUpdateEvent {
  * it returns the related SbbDatepickerElement reference, if exists.
  * @param element The element potentially connected to the SbbDatepickerElement.
  * @param trigger The id or the reference of the SbbDatePicker.
+ * @deprecated No longer in use.
```
Comment (jeripeierSBB) [inline src/elements/datepicker/datepicker/datepicker.ts:36]: Currently it's still used in tests. maybe possible to remove them right away?

File: src/elements/datepicker/common/datepicker-association-controllers.ts [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+import type { SbbDatepickerElement } from '../datepicker/datepicker.js';
+
+export interface SbbDatepickerControl<T> extends LitElement {
+  datepicker: SbbDatepickerElement<T> | null;
+}
+
+class SbbDatepickerAssociationContext<T> {
+  private static _registry = new WeakMap<Node, SbbDatepickerAssociationContext<any>>();
+
+  public readonly hosts = new Set<SbbDatepickerElement<T>>();
```
Comment (jeripeierSBB) [inline src/elements/datepicker/common/datepicker-association-controllers.ts:12]: for me it would be better encapsulated to not expose hosts and controls, but have specific "add" and "find" methods to interact with it, like deleteControls(). Not very important :)

File: src/elements/datepicker/common/datepicker-button.ts [hunk 3]
```diff
@@ -32,150 +62,70 @@ export abstract class SbbDatepickerButton<T = Date> extends SbbNegativeMixin(Sbb
   /** Whether the component is disabled due date-picker's input disabled. */
   private _inputDisabled = false;
 
+  /**
+   * @deprecated Use datepicker instead.
+   */
   protected datePickerElement?: SbbDatepickerElement<T> | null = null;
```
[the remark this answers is not in the document]
Comment (kyubisation) [reply src/elements/datepicker/common/datepicker-button.ts:68]: Yes, but protected is still technically part of the public API.

File: src/elements/datepicker/common/datepicker-button.ts [hunk 4]
```diff
@@ -32,150 +62,70 @@ export abstract class SbbDatepickerButton<T = Date> extends SbbNegativeMixin(Sbb
...
+      this._disabled = true;
       this.setAttribute('aria-label', this.i18nOffBoundaryDay[this._language.current]);
+      this._setDisabledRenderAttributes();
       return;
     }
 
+    const availableDate: T = this.findAvailableDate(this.datepicker.valueAsDate);
+    this._disabled =
+      this._dateAdapter.compareDate(availableDate, this.datepicker.valueAsDate) === 0;
+    this._inputDisabled = this.datepicker.inputElement?.disabled ?? true;
```
[the remark this answers is not in the document]
Comment (kyubisation) [reply src/elements/datepicker/common/datepicker-button.ts:104]: No, that is a mistake. Strange that I missed that.

File: src/elements/datepicker/common/datepicker-button.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (jeripeierSBB) [reply src/elements/datepicker/common/datepicker-button.ts:68]: ah you mean if someone has it's own datepicker-button inherited and own next / prev inherited, then it should still call datepickerelement in prev / next classes?.

File: src/elements/datepicker/datepicker/datepicker.ts (hunk 1 above)
Comment (kyubisation) [reply src/elements/datepicker/datepicker/datepicker.ts:36]: I think I would only remove the tests once we remove the function.

File: src/elements/datepicker/common/datepicker-association-controllers.ts (hunk 2 above)
Comment (kyubisation) [reply src/elements/datepicker/common/datepicker-association-controllers.ts:12]: I thought about that, but the controllers need access to the set and abstracting it with a getter felt overkill for a non-public API.

Comment (jeripeierSBB) [reply src/elements/datepicker/common/datepicker-association-controllers.ts:12]: it's ok like it is, but I meant not just getters but specific methods which interact with it (like filtering, or whatever manipulation)

File: src/elements/datepicker/datepicker/datepicker.ts (hunk 1 above)
Comment (jeripeierSBB) [reply src/elements/datepicker/datepicker/datepicker.ts:36]: Absolutely fine :-)

File: src/elements/datepicker/datepicker-next-day/readme.md [hunk 5]
```diff
@@ -38,7 +38,7 @@ both standalone or within the `sbb-form-field`, they must have the same parent e
 | Name         | Attribute     | Privacy | Type                                        | Default    | Description                                                 |
 | ------------ | ------------- | ------- | ------------------------------------------- | ---------- | ----------------------------------------------------------- |
 | `datepicker` | `datepicker`  | public  | `SbbDatepickerElement<T> \| null`           |            | Datepicker reference.                                       |
-| `datePicker` | `date-picker` | public  | `string \| SbbDatepickerElement<T> \| null` |            | Datepicker reference.                                       |
+| `datePicker` | `date-picker` | public  | `string \| SbbDatepickerElement<T> \| null` |            |                                                             |
```
[the remark this answers is not in the document]
Comment (kyubisation) [reply src/elements/datepicker/datepicker-next-day/readme.md]: Yep, that works 👍

**Review by jeripeierSBB — APPROVED** [review]
LGTM, nice fix
