### PR TITLE
fix(sbb-checkbox-group, sbb-radio-button-group): fix panel detection and styling

### LINKED ISSUE #3426: bug: radio & check panel within a group don't expand full width (Angular)
### Feature Description

Noticed in stories in Angular repo:
when several `sbb-checkbox-panel` are slotted in a `sbb-checkbox-group`, they don't occupy the page full width;
it seems that the `data-has-panel` attribute, which sets a 100% width, is not set on the group. 

Same for sbb-radio-button-group/panel.

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #3426

### CODE REVIEW

File: src/elements/checkbox/checkbox-group/checkbox-group.ts [hunk 1]
```diff
@@ -60,10 +60,7 @@ class SbbCheckboxGroupElement extends SbbDisabledMixin(LitElement) {
 
   public override connectedCallback(): void {
     super.connectedCallback();
-    this.toggleAttribute(
-      'data-has-panel',
-      !!this.querySelector?.('sbb-selection-expansion-panel, sbb-checkbox-panel'),
-    );
+    this.toggleAttribute('data-has-panel', !!this.querySelector?.('sbb-checkbox-panel'));
```
Comment (DavideMininni-Fincons) [inline src/elements/checkbox/checkbox-group/checkbox-group.ts:63]: Is the `selection-expansion-panel` not needed anymore? same for radio-group

**Review by DavideMininni-Fincons — APPROVED** [review]
LGTM!

File: src/elements/checkbox/checkbox-group/checkbox-group.ts (hunk 1 above)
Comment (jeripeierSBB) [reply src/elements/checkbox/checkbox-group/checkbox-group.ts:63]: I think not, as you never use a selection expansion panel without a containing checkbox or radio panel. with queryselector you will also find the underlaying checkbox panel or radio panel.

Comment (jeripeierSBB) [reply src/elements/checkbox/checkbox-group/checkbox-group.ts:63]: do you agree?
