### PR TITLE
fix(sbb-stepper): marker not visible in stepper

### LINKED ISSUE #3401: [Bug]: Styling of initial selectedIndex not always correct on Stepper element
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

2.0.1

### Operating system

macOS Sequoia 15.3.1

### Browser / Browser version

Mozilla Firefox 135.0 (aarch64)

### Input mode

Mouse/Keyboard

### Additional settings

_No response_

### What happened?

When using the Stepper element within a Dialog element, the initially selectedIndex (0) is not being styled correctly. Only after switching steps, the calculated progress bar appears. Sometimes, upon reinitializing the dialog/stepper, it seems to be working and the progress bar appears already on step 1 (selectedIndex 0), but this behavior is not always persistent.

### Steps to reproduce the issue

1. Goto: https://dev.sbb-immobilien.ch/bewerben-wohnen/?id=e19384f0-52d9-ef11-8eea-000d3a663091
2. Click on button "Person erfassen"
3. The dialog opens and shows the stepper, but the progress bar is missing
4. After filling out all the mandatory fields and clicking on button "Weiter", the progress bar correctly appears for step 2
5. The progress bar also behaves correctly when switching back to step 1

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #3401 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information on what is checked during the review process.

## Changes

Changes in this pull request:
if the sbb-stepper is used in a sbb-dialog, the marker on the selected element will not appear, because the calculations are done when the dialog is closed, so the marker has a width of 0.
We need to recalculate it when the element becomes visible and to do so a InterceptorController has been added.

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/elements/stepper/stepper/stepper.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { IntersectionController } from '@lit-labs/observers/intersection-controller.js';
```
Comment (jeripeierSBB) [inline src/elements/stepper/stepper/stepper.ts:1]: Only a simple question, would it work when adding setmarkersize to _onStepperResize ?

File: src/elements/stepper/stepper/stepper.ts [hunk 2]
```diff
@@ -29,6 +30,22 @@ export
 class SbbStepperElement extends SbbHydrationMixin(LitElement) {
   public static override styles: CSSResultGroup = style;
 
+  /**
```
Comment (jeripeierSBB) [inline src/elements/stepper/stepper/stepper.ts:33]: Could you create a test case covering the fix?

File: src/elements/stepper/stepper/stepper.ts (hunk 1 above)
Comment (jeripeierSBB) [reply src/elements/stepper/stepper/stepper.ts:1]: I mean instead of the intersectioncontroller

**Review by TomMenga — APPROVED** [review]
LGTM 👍 
As Jeri suggested, a visual spec of dialog + stepper would be nice

File: src/elements/stepper/stepper/stepper.ts (hunk 1 above)
Comment (TomMenga) [reply src/elements/stepper/stepper/stepper.ts:1]: I don't think it would be enough since the `window:resize` is not triggered when the dialog is opened

Comment (DavideMininni-Fincons) [reply src/elements/stepper/stepper/stepper.ts:1]: I confirm

> I don't think it would be enough since the `window:resize` is not triggered when the dialog is opened

File: src/elements/stepper/stepper/stepper.ts (hunk 2 above)
Comment (DavideMininni-Fincons) [reply src/elements/stepper/stepper/stepper.ts:33]: yes, sure, i'll update the pr soonish

**Comment by DavideMininni-Fincons** [comment]
PR updated with test
@jeripeierSBB @TomMenga 

Please note 
on the current (main) implementation there is this warning in the browser's console:
`step.ts:66 Element sbb-step scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.`

When I added the test with dialog + stepper, I received the mentioned warning and this error, which cause the test to fail:
`Error: ResizeObserver loop completed with undelivered notifications. (:0)`

This appears to be related to the sbb-step setting the height of the sbb-stepper via a ResizeObserver in the `firstUpdated` hook. To fix the error i removed the observer logic and I added a similar logic directly in the sbb-stepper: the warning is disappeared and the test does not fail anymore.

File: src/elements/stepper/stepper/stepper.ts [hunk 3]
```diff
@@ -29,6 +30,24 @@ export
...
+   * If the sbb-stepper is used in a sbb-dialog, the marker on the selected element will not appear,
+   * because the calculations are done when the dialog is closed, so the marker has a width of 0;
+   * the same happens for the stepper height.
+   * We need to recalculate it when the element becomes visible.
+   */
+  private _observer = new IntersectionController(this, {
+    target: null,
+    callback: (entries) => {
+      entries.forEach((e) => {
+        if (e.intersectionRatio === 1) {
```
Comment (jeripeierSBB) [inline src/elements/stepper/stepper/stepper.ts:43]: would that also work, if the element is half visible? or should we use something like "> 0"?

Comment (DavideMininni-Fincons) [reply src/elements/stepper/stepper/stepper.ts]: In this specific case, i see the interceptor going directly to 1 when the dialog is open; i feel we can relax the check with > 0

**Review by jeripeierSBB — APPROVED** [review]
LGTM :) some minor stuff found

File: src/elements/dialog/dialog/dialog.spec.ts [hunk 4]
```diff
@@ -587,4 +589,64 @@ describe('sbb-dialog', () => {
...
+      // Need to wait for the intersector to kick in; the value is set in px, so we have to remove the unit
+      await waitForCondition(
+        () =>
+          Number(
+            getComputedStyle(stepper)
+              .getPropertyValue('--sbb-stepper-marker-size')
+              .replaceAll('px', ''),
+          ) > 0,
+      );
+      console.log(getComputedStyle(stepper).getPropertyValue('--sbb-stepper-marker-size'));
```
[the remark this answers is not in the document]
Comment (DavideMininni-Fincons) [reply src/elements/dialog/dialog/dialog.spec.ts:643]: whoops

File: src/elements/stepper/stepper/stepper.ts [hunk 5]
```diff
@@ -183,6 +203,21 @@ class SbbStepperElement extends SbbHydrationMixin(LitElement) {
...
+  /**
+   * Sets the stepper height based on the height of the provided step.
+   */
+  private _setStepperHeight(step: SbbStepElement): void {
+    if (step && step.shadowRoot) {
+      const innerElement = step.shadowRoot.querySelector('.sbb-step');
+      if (innerElement) {
+        this.style?.setProperty(
+          '--sbb-stepper-content-height',
+          getComputedStyle(innerElement).getPropertyValue('height'),
```
[the remark this answers is not in the document]
Comment (DavideMininni-Fincons) [reply src/elements/stepper/stepper/stepper.ts]: No special thoughts behind getComputedStyle, I just remembered I used in some other test. Replaced.
