### PR TITLE
fix(sbb-image): make load event behave like native image

### LINKED ISSUE #3609: story(sbb-image): improve image loading mechanism
Currently we mimic the native behavior of image and we provide "complete" and the "load" event. we emit this once and stay in this state.
However, when there is a srcset (standard im sbb-image), whenever the viewport changes, it loads a new image. the native image seems then to send a new event.
We have to investigate the native behavior and try to mimic in sbb-image.

### PR DESCRIPTION
**Pull request by MarioCastigliano**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #3609 

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: src/elements/image/image.component.ts [hunk 1]
```diff
@@ -522,7 +510,7 @@ class SbbImageElement extends SbbElementInternalsMixin(LitElement) {
     this._logPerformanceMarks();
     this.internals.states.add('loaded');
 
-    /** Emits when the image has been loaded. */
+    /** Emits each time the image loads. */
```
Comment (jeripeierSBB) [inline src/elements/image/image.component.ts]: I think we should enhance the description a little bit to clarify?
```suggestion
    /** Emits each time an image loads. E.g. loading image for a different viewport, triggers the load event again. */
```

**Review by jeripeierSBB — COMMENTED** [review]
Thank you for the fix!

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thank you!
