### PR TITLE
fix(autocomplete): reposition correctly on dynamically adding options

### LINKED ISSUE #350: [Bug]: Autocomplete with lazy options hides input
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-angular/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-angular/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

    "@sbb-esta/lyne-elements": "4.10.0",     "@sbb-esta/lyne-angular": "21.6.0",

### Operating system

win11

### Browser / Browser version

chrome 

### Input mode

None

### Additional settings

_No response_

### What happened?

When the options of an autocomplete change while it is open the panel is not correctly repositioned.
When initially the panel with the options fit below and then additional options are added, so that the panel does not fit any more below, it is not positioned above, but somewhere inbetween. This hides the input where the user might be typing, which is bad.

### Steps to reproduce the issue

1. go to https://stackblitz.com/edit/1qhcbuyp?file=src%2Fapp%2Fautocomplete-basic-example.html
2. focus the input
3. wait 1 second
4. observe that the panel is positioned over the input, effectively hiding the input

Image

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kyubisation**
Closes sbb-design-systems/lyne-angular#350

### CODE REVIEW

File: src/elements/autocomplete/autocomplete-base-element.ts [hunk 1]
```diff
@@ -395,6 +400,13 @@ export abstract class SbbAutocompleteBaseElement<T = string> extends SbbNegative
   private _handleSlotchange(): void {
     this._highlightOptions(this.triggerElement?.value);
 
+    // It is possible that an option instance is added that has not been rendered
+    // yet and therefore has height 0. Due to this we also observe the size of the options.
+    const currentElements = Array.from(this.querySelectorAll('*'));
+    this._previousElements?.forEach((option) => this._resizeObserver.unobserve(option));
```
Comment (jeripeierSBB) [inline src/elements/autocomplete/autocomplete-base-element.ts]: "option" maybe not the most accurate name anymore

File: src/elements/autocomplete/autocomplete.stories.ts [hunk 2]
```diff
@@ -557,6 +557,19 @@ export const WithEllipsis: StoryObj = {
   args: { ...defaultArgs, ellipsis: true },
 };
 
+export const Repositiontest: StoryObj = {
```
Comment (jeripeierSBB) [inline src/elements/autocomplete/autocomplete.stories.ts]: I think we shouldn't add this story?

**Review by jeripeierSBB — APPROVED** [review]
LGTM, two comments
