### PR TITLE
fix(link): fix accessibility by inlining link functionality into Shadow DOM

### LINKED ISSUE #2514: Inline link functionality
We currently have the problem that the `role="presentation"` is ignored in the link base element in browsers. This causes issues in JAWS.
Due to this, with a heavy heart, we decided to abandon our current approach of defining the host as the link and move the logic back to the inner anchor element.
This means refactoring the link base element to not have role link, remove tabindex and the event listeners and adapt the styling of all inherited components.

### PR DESCRIPTION
**Pull request by TomMenga**
This PR Closes #2514, #2604, #2376, #2496

------

BEGIN_COMMIT_OVERRIDE
fix(sbb-link): fix accessibility by inlining link functionality into Shadow DOM

BREAKING CHANGE: Due to screen reader limitations, we had to move the `link` role inside the Shadow DOM. Therefore, for the following components, replace the `[aria-label]` usages with `[accessibility-label]` attribute or `accessibilityLabel` property:
- `sbb-breadcrumb`
- `sbb-button-link`, `sbb-secondary-button-link`, `sbb-tertiary-button-link`, `sbb-transparent-button-link`
- `sbb-card-link`
- `sbb-header-link`
- `sbb-link`, `sbb-block-link`
- `sbb-menu-link`
- `sbb-navigation-link`
- `sbb-teaser`, `sbb-teaser-hero`, `sbb-teaser-paid`

END_COMMIT_OVERRIDE

### CODE REVIEW

File: src/components/card/card-link/card-link.ts [hunk 1]
```diff
@@ -10,7 +10,9 @@ import { SbbCardActionCommonElementMixin } from '../common/index.js';
  *   This is relevant for SEO and screen readers.
  */
 @customElement('sbb-card-link')
-export class SbbCardLinkElement extends SbbCardActionCommonElementMixin(SbbLinkBaseElement) {}
+export class SbbCardLinkElement extends SbbCardActionCommonElementMixin(SbbLinkBaseElement) {
+  protected override actionRole: 'link' | 'button' = 'link';
```
Comment (DavideMininni-Fincons) [inline src/components/card/card-link/card-link.ts:14]:
```suggestion
  protected override actionRole = 'link';
```

File: src/components/card/card-button/card-button.ts [hunk 2]
```diff
@@ -10,7 +10,9 @@ import { SbbCardActionCommonElementMixin } from '../common/index.js';
  *   This is relevant for SEO and screen readers.
  */
 @customElement('sbb-card-button')
-export class SbbCardButtonElement extends SbbCardActionCommonElementMixin(SbbButtonBaseElement) {}
+export class SbbCardButtonElement extends SbbCardActionCommonElementMixin(SbbButtonBaseElement) {
+  protected override actionRole: 'link' | 'button' = 'button';
```
Comment (DavideMininni-Fincons) [inline src/components/card/card-button/card-button.ts:14]:
```suggestion
  protected override actionRole = 'button';
```

File: src/components/menu/common/menu-action-common.ts [hunk 3]
```diff
@@ -27,7 +27,7 @@ export const SbbMenuActionCommonElementMixin = <
   superClass: T,
 ): AbstractConstructor<SbbMenuActionCommonElementMixinType> & T => {
   abstract class SbbMenuActionCommonElement
-    extends SbbIconNameMixin(SbbDisabledTabIndexActionMixin(superClass))
+    extends SbbIconNameMixin(SbbDisabledMixin(superClass))
```
Comment (DavideMininni-Fincons) [inline src/components/menu/common/menu-action-common.ts:30]: I think this is correct for menu-link, but what about menu-button?

**Review by DavideMininni-Fincons — CHANGES_REQUESTED** [review]
Very good 👍 
General comment: the change from aria-label to accessibility-label must be added in the readme of all the components influenced by this changes.

File: src/components/card/card-link/card-link.ts (hunk 1 above)
Comment (TomMenga) [reply src/components/card/card-link/card-link.ts:14]: Unfortunately the linting gets angry at that :/

File: src/components/menu/common/menu-action-common.ts (hunk 3 above)
Comment (TomMenga) [reply src/components/menu/common/menu-action-common.ts:30]: Good catch, you're correct

File: src/components/link/link-button/link-button.spec.ts [hunk 4]
```diff
@@ -12,14 +12,7 @@ describe(`sbb-link-button`, () => {
...
     element = await fixture(html`
-      <sbb-link-button
-        name="name"
-        type="button"
-        form="form"
-        value="value"
-        size="m"
-        aria-label="Travelcards &amp; tickets"
-      >
+      <sbb-link-button name="name" type="button" form="form" value="value" size="m">
```
Comment (DavideMininni-Fincons) [inline src/components/link/link-button/link-button.spec.ts:15]: Old code has aria-label, is accessibility-label missing?

Comment (TomMenga) [reply src/components/link/link-button/link-button.spec.ts:15]: The mistake was to remove `aria-label` (because link-button extends `ButtonBase`)

**Review by jeripeierSBB — CHANGES_REQUESTED** [review]
Thanks for deep diving here! A few fixes needed and maybe more manual testing as I found some not working or wrongly displayed focus outlines?

File: src/components/skiplink-list/skiplink-list.stories.ts [hunk 5]
```diff
@@ -105,7 +105,7 @@ const playStory = async ({ canvasElement }: StoryContext): Promise<void> => {
     canvas.getByTestId('skiplink')?.shadowRoot?.querySelectorAll('.sbb-skiplink-list__wrapper'),
   );
   await waitForStablePosition(() => canvas.getByTestId('skiplink'));
-  userEvent.tab();
+  document.querySelector('sbb-block-link')?.focus();
```
[the remark this answers is not in the document]
Comment (TomMenga) [reply src/components/skiplink-list/skiplink-list.stories.ts:109]: I could neither find a solution nor the reason behind it.
It probably has to do with the fact that the `tab()` method is a simulation of the real tab and they probably cannot query focusable elements inside the shadowDom

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks for all the patience! :-). Please wait with merge, as we maybe have to release another non breaking fix.

**Review by DavideMininni-Fincons — APPROVED** [review]
LGTM, thanks
