### PR TITLE
fix(sbb-datepicker-toggle): fix datepicker toggle empty state synchronization

### LINKED ISSUE #3017: bug(datepicker): empty state not synchronized
Given the user choses a date with the datepicker-toggle and if he re-opens the calendar, the selection is still there (so far so good). If he changes the value in the input field and re-opens the calendar, it's synchronized (still good).
If the user deletes the date from the input and clicks the toggle, the old date is still selected in the calendar. 

Can be reproduced here: https://lyne-storybook.app.sbb.ch/?path=/story/elements-sbb-datepicker-sbb-datepicker-toggle--in-form-field

Goal: Calendar should be in sync with input and remove selected date on empty input.

### PR DESCRIPTION
**Pull request by dauriamarco**
Closes #3017

### CODE REVIEW

**Review by DavideMininni-Fincons — APPROVED** [review]
if it's possible and not too hard, i would like to have a test on it

File: src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts [hunk 1]
```diff
@@ -159,8 +159,8 @@ export class SbbDatepickerToggleElement<T = Date> extends SbbNegativeMixin(
 
   private _datePickerChanged(event: Event): void {
```
Comment (jeripeierSBB) [inline src/elements/datepicker/datepicker-toggle/datepicker-toggle.ts:160]: Please add a test that was failing before the change and is now successful :)

**Review by DavideMininni-Fincons — APPROVED** [review]

**Review by MarioCastigliano — APPROVED** [review]
Played with it a bit to make sure nothing was broken. Looks fine to me 👍
