### PR TITLE
fix: handle scroll events in custom scroll contexts

### LINKED ISSUE #3276: [Bug]: autocomplete drop-down does not scroll with content in scrollable sbb-dialog
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

_No response_

### Operating system

_No response_

### Browser / Browser version

_No response_

### Input mode

None

### Additional settings

_No response_

### What happened?

If a sbb-autocomplete is used in a sbb-dialog, which is scrollable caused by bigger content length than available, the sbb-autocomplete drop-down does not scroll on scrolling dialog content.

### Steps to reproduce the issue

1. use sbb-autocomplete in a sbb-dialog
2. add enough content to the dialog beside the input text, which has an attached sbb-autocomplete
3. focus input text, which opens autocomplete drop-down
4. scroll content
5. autocomplete drop-down is sticky and does not scroll with the input text

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #3276

### CODE REVIEW

File: src/elements/autocomplete/autocomplete-base-element.ts [hunk 1]
```diff
@@ -357,6 +357,7 @@ export abstract class SbbAutocompleteBaseElement extends SbbNegativeMixin(
     document.addEventListener('scroll', () => this._setOverlayPosition(), {
       passive: true,
       signal: this._openPanelEventsController.signal,
+      capture: true,
```
Comment (kyubisation) [inline src/elements/autocomplete/autocomplete-base-element.ts:360]: Should we document why we use capture here?

File: src/elements/menu/menu/menu.ts [hunk 2]
```diff
@@ -319,6 +320,7 @@ class SbbMenuElement extends SbbNamedSlotListMixin<
     document.addEventListener('scroll', () => this._setMenuPosition(), {
       passive: true,
       signal: this._windowEventsController.signal,
+      capture: true,
```
Comment (kyubisation) [inline src/elements/menu/menu/menu.ts:323]: Same

File: src/elements/popover/popover/popover.ts [hunk 3]
```diff
@@ -317,6 +317,7 @@ class SbbPopoverElement extends SbbHydrationMixin(SbbOpenCloseBaseElement) {
     document.addEventListener('scroll', () => this._setPopoverPosition(), {
       passive: true,
       signal: this._openStateController.signal,
+      capture: true,
```
Comment (kyubisation) [inline src/elements/popover/popover/popover.ts:320]: Same

File: src/elements/select/select.ts [hunk 4]
```diff
@@ -577,6 +577,7 @@ class SbbSelectElement extends SbbUpdateSchedulerMixin(
     document.addEventListener('scroll', () => this._setOverlayPosition(), {
       passive: true,
       signal: this._openPanelEventsController.signal,
+      capture: true,
```
Comment (kyubisation) [inline src/elements/select/select.ts:580]: Same

**Review by kyubisation — APPROVED** [review]
LGTM 👍

File: src/elements/dialog/dialog-content/dialog-content.ts [hunk 5]
```diff
@@ -16,7 +18,7 @@ class SbbDialogContentElement extends LitElement {
 
   protected override render(): TemplateResult {
     return html`
-      <div class="sbb-dialog-content">
+      <div class="sbb-dialog-content" @scroll=${(e: Event) => forwardEvent(e, document)}>
         <slot></slot>
       </div>
```
Comment (TomMenga) [inline src/elements/dialog/dialog-content/dialog-content.ts:23]: Out of curiosity, if we don't forward the scroll event the `capture` does not intercept it?

**Review by TomMenga — APPROVED** [review]
LGTM 👍

File: src/elements/dialog/dialog-content/dialog-content.ts (hunk 5 above)
Comment (jeripeierSBB) [reply src/elements/dialog/dialog-content/dialog-content.ts:23]: no, because the scroll event is not composed, so it stays inside shadow DOM, even when using capture.

**Review by DavideMininni-Fincons — APPROVED** [review]

**Review by kyubisation — APPROVED** [review]
LGTM 👍
