### PR TITLE
fix(sbb-clock): fix de-sync on long-running use cases

### LINKED ISSUE #3437: [Bug]: SbbClock has not exactly 60 seconds
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

_No response_

### Operating system

_No response_

### Browser / Browser version

_No response_

### Input mode

None

### Additional settings

_No response_

### What happened?

I used the SbbClock on a monitor, that is 24/7 on and showing the clock. But seems that clock needs for a real minute 61s or so. After ~24 hours, the clock differs about 30min compared to the real time.

Maybe the clock should be synchronised with the system clock or it must ensure that one minutes takes exactly 60 seconds and one hour exactly 60 minutes.

### Steps to reproduce the issue

1. Show the clock.
2. Let it run for long time.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by TomMenga**
This PR Closes #3437

### CODE REVIEW

File: src/elements/clock/clock.ts [hunk 1]
```diff
@@ -81,12 +87,20 @@ class SbbClockElement extends LitElement {
...
   /** Callback function for hours hand. */
   private _moveHoursHandFn = (): void => this._moveHoursHand();
 
   /** Callback function for minutes hand. */
   private _moveMinutesHandFn = (): void => this._moveMinutesHand();
 
+  public override connectedCallback(): void {
+    super.connectedCallback();
+
+    this._resetIntervalID = setInterval(() => this._resetClock(), RESET_INTERVAL * 1000);
```
Comment (kyubisation) [inline src/elements/clock/clock.ts:101]: Nitpick; I think when we use the term `Id`, the d is lowercase.

**Review by kyubisation — APPROVED** [review]
LGTM 👍

**Review by jeripeierSBB — APPROVED** [review]
LGTM. thank you!
