### PR TITLE
fix(sbb-select, sbb-autocomplete): edge cases related to disabled property

### LINKED ISSUE #3518: bug: disabled state on select and autocomplete
Two separate issues:
- sbb-select enabled / all options disabled: the arrow navigation is broken because it can't tell what's the nextElement
 
- sbb-autocomplete enabled -> open, dropdown visible -> disable set to true on the input -> panel stays open and options are still clickable 
solution: close the panel as in the select

### PR DESCRIPTION
**Pull request by DavideMininni-Fincons**
## Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [pull request tracker](https://github.com/sbb-design-systems/lyne-components/pulls) for a Pull Request (PR) that matches the one I want to submit, without success.

## Issue

This PR Closes #3518

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)

See [Review Guidelines](../docs/REVIEW.md) for more information on what is checked during the review process.

## Changes

Changes in this pull request:

- close the autocomplete/autocomplete-grid if it's open and the `disabled` prop changes to true
- in sbb-select, avoid throwing error if all the options are disabled and arrow keys are pressed

## Browsers

I tested the build on the following browsers:

- [ ] Firefox Desktop
- [x] Chrome Desktop
- [ ] Edge Desktop
- [ ] Safari Desktop
- [ ] Chrome Mobile
- [ ] Safari Mobile

## Screen readers

I tested the build on the following browsers:

- [ ] JAWS Firefox Desktop
- [ ] JAWS Chrome Desktop
- [ ] NVDA Firefox Desktop
- [ ] NVDA Chrome Desktop
- [ ] VoiceOver Safari Desktop
- [ ] VoiceOver Chrome Desktop
- [ ] VoiceOver Safari Mobile
- [ ] Android Accessibility Suite Chrome Mobile

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/elements/form-field/form-field/form-field.ts [hunk 1]
```diff
@@ -443,6 +444,11 @@ class SbbFormFieldElement extends SbbNegativeMixin(SbbHydrationMixin(LitElement)
     }
     this.toggleAttribute('data-readonly', this._input.hasAttribute('readonly'));
     this.toggleAttribute('data-disabled', this._input.hasAttribute('disabled'));
+    if (this._input.hasAttribute('disabled')) {
+      this.querySelector<SbbAutocompleteBaseElement>(
+        'sbb-autocomplete,sbb-autocomplete-grid',
+      )?.close();
+    }
```
[the remark this answers is not in the document]
Comment (DavideMininni-Fincons) [reply src/elements/form-field/form-field/form-field.ts:451]: The close method in the ac/ac-grid has the following logic, preventing closing if the state is not `opened`.
```
public close(): void {
    if (this.state !== 'opened') {
      return;
    }
    ...
}
```

File: src/elements/select/select.ts [hunk 2]
```diff
@@ -794,6 +794,11 @@ class SbbSelectElement extends SbbUpdateSchedulerMixin(
   }
 
   private _setNextActiveOption(event: KeyboardEvent, index?: number): void {
+    // Prevent keyboard navigation if all options are disabled
+    if (this._filteredOptions.length === 0) {
```
Comment (jeripeierSBB) [inline src/elements/select/select.ts:798]: I propose to cache filteredoptions in this method as it is called several times.

**Review by jeripeierSBB — APPROVED** [review]
Nice fixes. thank you

File: src/elements/form-field/form-field/form-field.ts [hunk 3]
```diff
@@ -443,6 +444,11 @@ class SbbFormFieldElement extends SbbNegativeMixin(SbbHydrationMixin(LitElement)
     }
     this.toggleAttribute('data-readonly', this._input.hasAttribute('readonly'));
     this.toggleAttribute('data-disabled', this._input.hasAttribute('disabled'));
+    if (this._input.hasAttribute('disabled')) {
```
Comment (jeripeierSBB) [inline src/elements/form-field/form-field/form-field.ts:447]: Maybe it's nicer to move this into the autocomplete? the trigger is there and then it works also for input elements not inside a form field.

Comment (DavideMininni-Fincons) [reply src/elements/form-field/form-field/form-field.ts]: I agree, I added a listener for both disabled and readonly properties on the trigger
