### PR TITLE
fix(sbb-image): render URL correctly with SSR

### LINKED ISSUE #2690: [Bug]: SSR issue with sbb-image
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.51.1

### Operating system

MacOS 14.3

### Browser / Browser version

Chrome 125.0.6422.113

### Input mode

None

### Additional settings

_No response_

### What happened?

After SSR, `sbb-image`'s `source`-element has invalid values for the `srcset`-property.

### Steps to reproduce the issue

1. open https://codesandbox.io/p/devbox/lyne-image-issue-dzsht5
2. make sure the server is running, otherwise run `npm start` on the terminal.
3. open the preview in a new tab
4. inspect the `sbb-image` element, specifically the `source` elements.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kyubisation**
Closes #2690

### CODE REVIEW

File: src/elements/image/image.ts [hunk 1]
```diff
@@ -437,7 +439,9 @@ export class SbbImageElement extends LitElement {
       imageUrlObj.searchParams.append('fp-debug', 'true');
     }
 
-    return imageUrlObj.href;
+    return isFullyQualifiedUrl
+      ? imageUrlObj.href
+      : imageUrlObj.pathname.substring(1) + imageUrlObj.search;
```
Comment (jeripeierSBB) [inline src/elements/image/image.ts:444]:
```suggestion
    // In case of "noop" host, we don't return the host and must remove the starting `/` of the pathname.
    return isFullyQualifiedUrl
      ? imageUrlObj.href
      : imageUrlObj.pathname.substring(1) + imageUrlObj.search;
```

**Review by jeripeierSBB — APPROVED** [review]
Great, I like that we can save it in a test now :-)
