### PR TITLE
fix(sbb-option): correctly determine highlight state with SSR

### LINKED ISSUE #2689: [Bug]: SSR issue with sbb-option
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.51.1

### Operating system

MacOS 14.3

### Browser / Browser version

Chrome 125.0.6422.113

### Input mode

None

### Additional settings

_No response_

### What happened?

After SSR, the `sbb-option` inside an `sbb-select` does not get rendered properly.

### Steps to reproduce the issue

1. open https://codesandbox.io/p/devbox/lyne-option-issue-ytc3xy
2. make sure the server is running, otherwise run `npm start` on the terminal.
3. open the preview in a new tab
4. inspect the `sbb-option` elements when opening the `sbb-select` element.

### Relevant log output

```shell
-
```

### PR DESCRIPTION
**Pull request by kyubisation**
Closes #2689

### CODE REVIEW

File: src/elements/option/option/option.ts [hunk 1]
```diff
@@ -273,13 +277,13 @@ export class SbbOptionElement extends SbbDisabledMixin(SbbIconNameMixin(LitEleme
...
 
-  private _setupHighlightHandler(event: Event): void {
+  private _handleHighlightState(): void {
     if (!this._isAutocomplete) {
       this._updateDisableHighlight(true);
       return;
     }
 
-    const slotNodes = (event.target as HTMLSlotElement).assignedNodes();
+    const slotNodes = Array.from(this.childNodes ?? []);
```
Comment (jeripeierSBB) [inline src/elements/option/option/option.ts:286]: What's the sense of this line change?

**Review by jeripeierSBB — APPROVED** [review]
LGTM, thanks!

File: src/elements/option/option/option.ts (hunk 1 above)
Comment (kyubisation) [reply src/elements/option/option/option.ts:286]: The previous logic depended on the event, but with the change in calling it in connectedCallback, I have no event in that case.
I just realized there is a small distinction. I have to exclude elements that are assigned to the image slot.
